### ISSUE TITLE
Pricing buttons look odd?

### ISSUE THREAD

**Issue by edireson** [laughing-waffles/transfervox#3] opened 2022-06-07 22:04 UTC
![Screen Shot 2022-06-07 at 5 03 42 PM](https://user-images.githubusercontent.com/368674/172490677-e9332511-2a81-421d-9f2b-331bd98325c7.png)

**Comment by judsonlmoore** [comment] 2022-06-08 14:25
@edireson can you provide more info on browser and url? I see this: 
<img width="823" alt="image" src="https://user-images.githubusercontent.com/52468936/172641494-cd74f4b8-5115-475f-a546-194e09c975d2.png">

**Comment by judsonlmoore** [comment] 2022-06-08 14:25
ah ok I can reproduce on safari

**Comment by judsonlmoore** [comment] 2022-06-08 14:43
Resolved with [Make buttons safe for safari](https://github.com/laughing-waffles/transfervox/commit/d735b0ac3e7cbb4bf4a3521dc06e2889fe7c32ea)

**Comment by judsonlmoore** [comment] 2022-06-08 14:44
Now safari looks like this 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/52468936/172645802-714e1ed7-53e8-4be2-9cdf-f08dc0b18253.png">

**Closed as completed by judsonlmoore** 2022-06-08 14:43 UTC
